// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOIk2K4t5aiBOhJk43zcCKFVi5bQY0ecE',
    appId: '1:70685610461:web:3b2d0c93e92627431ca634',
    messagingSenderId: '70685610461',
    projectId: 'jayslivestock-c3f77',
    authDomain: 'jayslivestock-c3f77.firebaseapp.com',
    storageBucket: 'jayslivestock-c3f77.firebasestorage.app',
    measurementId: 'G-ZKKLV59L67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPCIKVEEuVVoTR8mCVox2WhXSWWuJbTOM',
    appId: '1:70685610461:android:675e5210b6c8cd801ca634',
    messagingSenderId: '70685610461',
    projectId: 'jayslivestock-c3f77',
    storageBucket: 'jayslivestock-c3f77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh9NznyaCMbidC6lMUevREnkatptsIhfw',
    appId: '1:70685610461:ios:1f2a42fc3937deb21ca634',
    messagingSenderId: '70685610461',
    projectId: 'jayslivestock-c3f77',
    storageBucket: 'jayslivestock-c3f77.firebasestorage.app',
    iosBundleId: 'com.example.scan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh9NznyaCMbidC6lMUevREnkatptsIhfw',
    appId: '1:70685610461:ios:1f2a42fc3937deb21ca634',
    messagingSenderId: '70685610461',
    projectId: 'jayslivestock-c3f77',
    storageBucket: 'jayslivestock-c3f77.firebasestorage.app',
    iosBundleId: 'com.example.scan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOIk2K4t5aiBOhJk43zcCKFVi5bQY0ecE',
    appId: '1:70685610461:web:a65b1eb4ab3d56141ca634',
    messagingSenderId: '70685610461',
    projectId: 'jayslivestock-c3f77',
    authDomain: 'jayslivestock-c3f77.firebaseapp.com',
    storageBucket: 'jayslivestock-c3f77.firebasestorage.app',
    measurementId: 'G-MBJS3ESRC8',
  );
}
